query ($organization: String!, $repository: String!, $number: Int!) {
  repository(owner: $organization, name: $repository) {
    issue(number: $number) {
      id
      number
      title
      url
      body
      reactions(first: 100) {
        nodes {
          content
        }
      }
      subIssues(first: 10) {
        nodes {
          title
          url
          body
          reactions(first: 100) {
            nodes {
              content
            }
          }
          author {
            login
            avatarUrl
            url
            ... on User {
              name
            }
          }
        }
      }
      subIssuesSummary {
        total
        completed
        percentCompleted
      }
    }
  }
}
