query (
  $organization: String!
  $repository: String!
  $state: [IssueState!]
  $first: Int
) {
  repository(owner: $organization, name: $repository) {
    issues(
      first: $first
      states: $state
      orderBy: { field: CREATED_AT, direction: DESC }
      labels: "DEFAULT_LABEL"
    ) {
      nodes {
        id
        number
        title
        url
        body
        reactions(first: 100) {
          nodes {
            content
          }
        }
        subIssues(first: 10) {
          nodes {
            title
            body
            reactions(first: 100) {
              nodes {
                content
              }
            }
            author {
              login
              avatarUrl
              url
            }
          }
        }
        subIssuesSummary {
          total
          completed
          percentCompleted
        }
      }
    }
  }
}
