name: Test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!main'
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: false

jobs:
  test:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test
